<?php

/**
 * This code is licensed under the BSD 3-Clause License.
 *
 * Copyright (c) 2017, Maks Rafalko
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

declare(strict_types=1);

namespace Raneomik\InfectionTestFramework\Tester\Script\Template;

use function array_values;
use function sprintf;
use function var_export;

/**
 * Template for generating the Tester job prepend script.
 * Simplified: assumes autoload is already loaded by Tester's bootstrap.php
 */
final class AutoPrependTemplate
{
    /**
     * Generate the prepend script content.
     *
     * @param string $autoload Path to autoload file
     * @param string $fragmentDir Directory for coverage fragments
     * @param string[] $srcDirs Source directories to cover
     *
     * @return string Complete PHP script content
     */
    public static function build(
        string $autoload,
        string $fragmentDir,
        array $srcDirs,
    ): string {
        return sprintf(<<<'PHP'
<?php
/**
 * Auto-prepend script for coverage collection
 * Generated by Infection Tester Adapter
 *
 * Executed via auto_prepend_file before bootstrap.php
 */

declare(strict_types=1);

require_once %s;

\Raneomik\InfectionTestFramework\Tester\Script\CoverageRuntime::start(
    %s,
    %s,
);

PHP,
            var_export($autoload, true),
            var_export($fragmentDir, true),
            var_export(array_values($srcDirs), true),
        );
    }
}
